#cloud-config
shell: /bin/bash

write_files:
- path: /usr/lib/server.js
  append: true
  content: |
    const server = require('express')();
    const http = require('http').createServer(server);
    const io = require('socket.io')(http);

    /*
    const sio = require("socket.io")(http, {
        handlePreflightRequest: (req, res) => {
            const headers = {
                "Access-Control-Allow-Headers": "Content-Type, Authorization",
                "Access-Control-Allow-Origin": req.headers.origin, //or the specific origin you want to give access to,
                "Access-Control-Allow-Credentials": true
            };
            res.writeHead(200, headers);
            res.end();
        }
    });
    */

    /*
    //CORS HEADERS
    server.use(function(req, res, next) {
        res.header("Access-Control-Allow-Origin", "*");
        res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization");
        res.header('Access-Control-Allow-Methods', 'PUT, POST, GET, DELETE, OPTIONS');
        next();
    });
    */
    /*
        The server started and listens on port 4200
    */
    http.listen(4200, function () {
        console.log('Nile Dragons server started!');
        console.log('I am on localhost listening on port 4200 ^_^');
    });

    /*
        This array will hold the socket ids of the two players
    */
    let players = [];

    io.on('connection', function (socket) {
        console.log('A user connected: ' + socket.id);

        players.push(socket.id);

        if (players.length === 1) {
            io.emit('isPlayerA');
        };

        socket.on('disconnect', function () {
            console.log('A user disconnected: ' + socket.id);
            players = players.filter(player => player !== socket.id);
        });
    });



runcmd:
- sudo apt-get install curl
- curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
- sudo apt-get install nodejs -y 
- sudo apt install npm
- npm init -y
- sudo npm install --save -g nodemon
- sudo npm install --save -g express
- sudo npm install --save -g socket.io
- echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
- nodemon /usr/lib/server.js

